CopadoAX_Core/main/default/objects/copado__User_Story__c/copado__User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CopadoAX_Core/main/default/objects/copado__User_Story__c/fields/copado__Environment__c.field-meta.xml
<CustomField>
    <fullName>copado__Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
    <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>copado__Environment__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

CopadoAX_Core/main/default/objects/copado__User_Story__c/fields/copado__Has_Apex_Code__c.field-meta.xml
<CustomField>
    <fullName>copado__Has_Apex_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value automatically updated by Copado whenever there are Apex Classes added or committed in the User Story.</description>
    <inlineHelpText>Value automatically updated by Copado whenever there are Apex Classes added or committed in the User Story.</inlineHelpText>
    <label>Has Apex Code</label>
    <type>Checkbox</type>
</CustomField>

CopadoAX_Core/main/default/objects/copado__User_Story__c/fields/copado__Org_Credential__c.field-meta.xml
<CustomField>
    <fullName>copado__Org_Credential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
    <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
    <label>Org Credential</label>
    <referenceTo>copado__Org__c</referenceTo>
    <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

CopadoAX_Core/main/default/objects/copado__User_Story__c/fields/copado__Project__c.field-meta.xml
<CustomField>
    <fullName>copado__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project where the User Story belongs.</description>
    <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
    <label>Project</label>
    <referenceTo>copado__Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

CopadoAX_Core/main/default/objects/copado__User_Story__c/fields/copado__Promote_Change__c.field-meta.xml
<CustomField>
    <fullName>copado__Promote_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the User Story is marked as ready to be promoted. The user story will appear as &#39;Ahead&#39; and available to be selected in the Branch Management and Promotion pages.</description>
    <inlineHelpText>If checked, the User Story is marked as ready to be promoted. The user story will appear as &#39;Ahead&#39; and available to be selected in the Promotion and Branch Management pages.</inlineHelpText>
    <label>Ready to Promote</label>
    <type>Checkbox</type>
</CustomField>

CopadoAX_Core/main/default/classes/CopadoUserStoryService.cls
/**
 * Created by kheidt.
 */

public with sharing class CopadoUserStoryService {

    public static boolean hasApexCode = false;

    public static Map<Id, copado__User_Story__c> getUserStoriesToBePromoted(String projectId, String envId){
        Map<Id,copado__User_Story__c> stories = new Map<Id, copado__User_Story__c>([
                SELECT
                        Id,
                        Name,
                        copado__Environment__c,
                        copado__Org_Credential__c,
            			copado__Has_Apex_Code__c 
                FROM copado__User_Story__c
                WHERE
                        copado__Project__c = :projectId AND
                        copado__Environment__c = :envId AND
                        copado__Promote_Change__c = TRUE
        ]);

        return stories;
    }

    public static copado__User_Story__c getUserStory(String usId){
        copado__User_Story__c us = [
                SELECT
                        Id,
                        Name,
                        copado__Org_Credential__c,
                        copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c,
                        copado__Project__r.copado__Deployment_Flow__r.copado__Static_Code_Analysis_Settings__c,
            			copado__Has_Apex_Code__c 
                FROM copado__User_Story__c
                WHERE Id = :usId
                LIMIT 1
        ];
        return us;
    }

    public static Map<Id, List<Id>> getStoriesFromPromotions(List<Id> promoIds){
        Map<Id,List<Id>> promotionStoriesMap = new Map<Id, List<Id>>();
        List<copado__Promoted_User_Story__c> pus = new List<copado__Promoted_User_Story__c>([
                SELECT Id, Name, copado__Promotion__c, copado__User_Story__c, copado__User_Story__r.copado__Has_Apex_Code__c
                FROM copado__Promoted_User_Story__c
                WHERE copado__Promotion__c IN :promoIds
        ]);

        for(copado__Promoted_User_Story__c pusItem : pus){
            if(promotionStoriesMap.get(pusItem.copado__Promotion__c) == null){
                promotionStoriesMap.put(pusItem.copado__Promotion__c, new List<Id>());
            }
            promotionStoriesMap.get(pusItem.copado__Promotion__c).add(pusItem.copado__User_Story__c);
            if(pusItem.copado__User_Story__r.copado__Has_Apex_Code__c){
                hasApexCode = true;
            }
        }

        return promotionStoriesMap;
    }
}